// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaQqR7d-aTGjAteu7MFV8fv9Trm6Maj78',
    appId: '1:523845575062:web:8c6f9b797bf93accf2bdb7',
    messagingSenderId: '523845575062',
    projectId: 'chateo-72766',
    authDomain: 'chateo-72766.firebaseapp.com',
    storageBucket: 'chateo-72766.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR2pCII25R74xIPp1L8yCJcS8OgODPXiM',
    appId: '1:523845575062:android:02f9dbda4066b94ef2bdb7',
    messagingSenderId: '523845575062',
    projectId: 'chateo-72766',
    storageBucket: 'chateo-72766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSGYcgWwrnzz1BkOBLgOvSz4-LUSUWnR4',
    appId: '1:523845575062:ios:796f8525090ad8cdf2bdb7',
    messagingSenderId: '523845575062',
    projectId: 'chateo-72766',
    storageBucket: 'chateo-72766.appspot.com',
    iosClientId: '523845575062-4cd3u05lsf1su6lrovus8f97p9kcba6l.apps.googleusercontent.com',
    iosBundleId: 'com.meesum.chateo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSGYcgWwrnzz1BkOBLgOvSz4-LUSUWnR4',
    appId: '1:523845575062:ios:f60a2334ea4a9f86f2bdb7',
    messagingSenderId: '523845575062',
    projectId: 'chateo-72766',
    storageBucket: 'chateo-72766.appspot.com',
    iosClientId: '523845575062-bai5tqdnv4uhdkme7v0jgvaofmntp9ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.chateo',
  );
}
